app_id: dev
env: dev 

#strategy internal logic period
sleep_ms: 300

board_config:
  exchange: dydx
  #source : binance
  market: future
  coin_pairs:
   - btc/usd
  dbsync: False
 
model: 
  type : dydx-mm#1
  order_unit : 1000
  orderbook: dydx_orderbook
  trade: dydx_trade
  order_execution: dydx_account
  
boards:
  binance_account:
    type: account
    exchange: binance
    market: future
    coin_pairs:
     - btc/usdt
 
  dydx_account:
    type: account

  dydx_orderbook:
    type: orderbook
    commands:
      - 
       type : ws
       command : orderbook

  dydx_trade:
     type: trade
     commands:
       - 
        type : ws
        command : trade

ws_debug_port: 2021
