app_id: dev
env: dev 

#strategy internal logic period
sleep_ms: 10

board_config:
  exchange: dydx
  market: future
  coin_pairs:
   - eth/usd
  dbsync: False
 
model: 
  type : dydx-mm#1
 
mongodb:
  db:  market
  address: mongo_prod:27017
  #address: mongo1:27017
  rs: rs0
  id: hermes
  password: hermes1818 

boards:
  dydx_account:
    type: account
  dydx_orderbook:
    type: orderbook
    commands:
      - 
       type : ws
       command : orderbook

  dydx_trade:
     type: trade
     commands:
       - 
        type : ws
        command : trade
 
  binance_account:
    type: account
    exchange: binance
    market: future
    coin_pairs:
     - eth/usdt
  binance_trade:
    type: trade
    coin_pairs:
      - 'eth/usdt'
    exchange: binance
    commands:
      - 
        command : aggTrade
  binance_liquidation:
    type : liquidation
    coin_pairs:
     - 'eth/usdt'
    exchange: binance
    commands:
      - 
        market : future
        type : ws
        command : liquidation
  binance_candle: 
    type: candle
    coin_pairs:
      - 'eth/usdt'
    exchange: binance
    init:
       - 
        interval: '1m'
  binance_orderbook:
    type: orderbook
    coin_pairs:
      - 'eth/usdt'
    exchange: binance
    commands:
      - 
        type : ws
        command : orderbook
        interval: 100ms
        source : binance
    reset:
      - 
        command : orderbook
ws_debug_port: 2021
